export const GET_MOVIE_LIST_ALL = 'GET_MOVIE_LIST_ALL'
export const MOVIE_LIST_CHANGE_PAGE = 'MOVIE_LIST_CHANGE_PAGE'
export const MOVIE_LIST_LIKED_ADD = 'MOVIE_LIST_LIKED_ADD'
export const MOVIE_LIST_BLOCKED_ADD = 'MOVIE_LIST_BLOCKED_ADD'
export const MOVIE_LIST_UNLIKE = 'MOVIE_LIST_UNLIKE'
export const MOVIE_LIST_UNBLOCK = 'MOVIE_LIST_UNBLOCK'

